#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webtest2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Database1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteFromIngredient")]
		public int DeleteFromIngredient([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteFromProcedure")]
		public int DeleteFromProcedure([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllIngredients")]
		public ISingleResult<GetAllIngredientsResult> GetAllIngredients()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllIngredientsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllIngredientsforDelete")]
		public ISingleResult<GetAllIngredientsforDeleteResult> GetAllIngredientsforDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IngredientID", DbType="Int")] System.Nullable<int> ingredientID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ingredientID);
			return ((ISingleResult<GetAllIngredientsforDeleteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllProcedures")]
		public ISingleResult<GetAllProceduresResult> GetAllProcedures()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllProceduresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetIngredients")]
		public ISingleResult<GetIngredientsResult> GetIngredients([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quantity", DbType="Int")] System.Nullable<int> quantity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Unit", DbType="NVarChar(50)")] string unit, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ingredients", DbType="NVarChar(MAX)")] string ingredients)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), quantity, unit, ingredients);
			return ((ISingleResult<GetIngredientsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetProcedures")]
		public ISingleResult<GetProceduresResult> GetProcedures([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Procedures", DbType="NVarChar(MAX)")] string procedures)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), procedures);
			return ((ISingleResult<GetProceduresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRecipeID")]
		public ISingleResult<GetRecipeIDResult> GetRecipeID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<GetRecipeIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRecipeIDfordelete")]
		public ISingleResult<GetRecipeIDfordeleteResult> GetRecipeIDfordelete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<GetRecipeIDfordeleteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRecipeName")]
		public ISingleResult<GetRecipeNameResult> GetRecipeName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((ISingleResult<GetRecipeNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertIntoIngredients")]
		public int InsertIntoIngredients([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecipeID", DbType="Int")] System.Nullable<int> recipeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quantity", DbType="Int")] System.Nullable<int> quantity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Unit", DbType="NVarChar(50)")] string unit, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ingredients", DbType="NVarChar(MAX)")] string ingredients, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recipeID, quantity, unit, ingredients, id);
			id = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertIntoProcedure")]
		public int InsertIntoProcedure([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecipeID", DbType="Int")] System.Nullable<int> recipeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Procedure", DbType="NVarChar(MAX)")] string procedure, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recipeID, procedure, id);
			id = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertIntoRecipe")]
		public ISingleResult<InsertIntoRecipeResult> InsertIntoRecipe([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecipeName", DbType="NVarChar(50)")] string recipeName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Difficulty", DbType="NChar(10)")] string difficulty, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecipeType", DbType="NVarChar(50)")] string recipeType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="NVarChar(MAX)")] string comment)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recipeName, difficulty, recipeType, comment);
			return ((ISingleResult<InsertIntoRecipeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertItoImage")]
		public int InsertItoImage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary image)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), image);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mainProcedure")]
		public ISingleResult<mainProcedureResult> mainProcedure([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string recipeName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string recipeType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> quantity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string unit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> procedureId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recipeName, recipeType, quantity, unit, procedureId);
			return ((ISingleResult<mainProcedureResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetIngredientsbyRecipeID")]
		public ISingleResult<GetIngredientsbyRecipeIDResult> GetIngredientsbyRecipeID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecipeID", DbType="Int")] System.Nullable<int> recipeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recipeID);
			return ((ISingleResult<GetIngredientsbyRecipeIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertIntoMyRecipe")]
		public ISingleResult<InsertIntoMyRecipeResult> InsertIntoMyRecipe([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IngredientID", DbType="Int")] System.Nullable<int> ingredientID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> procedureID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> recipeID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string recipeName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string recipeType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ingredientID, procedureID, recipeID, recipeName, recipeType);
			return ((ISingleResult<InsertIntoMyRecipeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteTotalrecipe")]
		public int DeleteTotalrecipe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ingredientID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> procedureID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> recipeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ingredientID, procedureID, recipeID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetProcedureID")]
		public ISingleResult<GetProcedureIDResult> GetProcedureID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecipeId", DbType="Int")] System.Nullable<int> recipeId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recipeId);
			return ((ISingleResult<GetProcedureIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetIngredientID")]
		public ISingleResult<GetIngredientIDResult> GetIngredientID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecipeId", DbType="Int")] System.Nullable<int> recipeId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recipeId);
			return ((ISingleResult<GetIngredientIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DelteFromRecipe")]
		public int DelteFromRecipe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> recipeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recipeID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllRecipe")]
		public ISingleResult<GetAllRecipeResult> GetAllRecipe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string recipename, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string recipetype)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recipename, recipetype);
			return ((ISingleResult<GetAllRecipeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRecipeIngredients")]
		public ISingleResult<GetRecipeIngredientsResult> GetRecipeIngredients([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecipeID", DbType="Int")] System.Nullable<int> recipeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recipeID);
			return ((ISingleResult<GetRecipeIngredientsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertAdditionalIngredient")]
		public int InsertAdditionalIngredient([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string ingredient, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string unit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> quantity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> recipeid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ingredient, unit, quantity, recipeid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRecipeInfo")]
		public ISingleResult<GetRecipeInfoResult> GetRecipeInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<GetRecipeInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateRecipeInfo")]
		public int UpdateRecipeInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string recipename, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string recipetype, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string difficulty, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string comment, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> recipeid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recipename, recipetype, difficulty, comment, recipeid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertAdditionalProcedure")]
		public int InsertAdditionalProcedure([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string myprocedure, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> recipeid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), myprocedure, recipeid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRecipeProcedures")]
		public ISingleResult<GetRecipeProceduresResult> GetRecipeProcedures([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecipeID", DbType="Int")] System.Nullable<int> recipeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recipeID);
			return ((ISingleResult<GetRecipeProceduresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteFromAddedIngredient")]
		public int DeleteFromAddedIngredient([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteFromaddedProcedure")]
		public int DeleteFromaddedProcedure([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRecipeIngredientsResult")]
		public ISingleResult<GetRecipeIngredientsResultResult> GetRecipeIngredientsResult([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetRecipeIngredientsResultResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRecipeIngredient")]
		public ISingleResult<GetRecipeIngredientResult> GetRecipeIngredient([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecipeID", DbType="Int")] System.Nullable<int> recipeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recipeID);
			return ((ISingleResult<GetRecipeIngredientResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetAllIngredientsResult
	{
		
		private int _IngredientId;
		
		private int _RecipeID;
		
		private int _Quantity;
		
		private string _Unit;
		
		private string _Ingredient;
		
		public GetAllIngredientsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientId", DbType="Int NOT NULL")]
		public int IngredientId
		{
			get
			{
				return this._IngredientId;
			}
			set
			{
				if ((this._IngredientId != value))
				{
					this._IngredientId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeID", DbType="Int NOT NULL")]
		public int RecipeID
		{
			get
			{
				return this._RecipeID;
			}
			set
			{
				if ((this._RecipeID != value))
				{
					this._RecipeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ingredient", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Ingredient
		{
			get
			{
				return this._Ingredient;
			}
			set
			{
				if ((this._Ingredient != value))
				{
					this._Ingredient = value;
				}
			}
		}
	}
	
	public partial class GetAllIngredientsforDeleteResult
	{
		
		private int _IngredientId;
		
		private int _RecipeID;
		
		private int _Quantity;
		
		private string _Unit;
		
		private string _Ingredient;
		
		public GetAllIngredientsforDeleteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientId", DbType="Int NOT NULL")]
		public int IngredientId
		{
			get
			{
				return this._IngredientId;
			}
			set
			{
				if ((this._IngredientId != value))
				{
					this._IngredientId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeID", DbType="Int NOT NULL")]
		public int RecipeID
		{
			get
			{
				return this._RecipeID;
			}
			set
			{
				if ((this._RecipeID != value))
				{
					this._RecipeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ingredient", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Ingredient
		{
			get
			{
				return this._Ingredient;
			}
			set
			{
				if ((this._Ingredient != value))
				{
					this._Ingredient = value;
				}
			}
		}
	}
	
	public partial class GetAllProceduresResult
	{
		
		private int _ProcedureId;
		
		private int _RecipeId;
		
		private string _MyProcedure;
		
		public GetAllProceduresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcedureId", DbType="Int NOT NULL")]
		public int ProcedureId
		{
			get
			{
				return this._ProcedureId;
			}
			set
			{
				if ((this._ProcedureId != value))
				{
					this._ProcedureId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeId", DbType="Int NOT NULL")]
		public int RecipeId
		{
			get
			{
				return this._RecipeId;
			}
			set
			{
				if ((this._RecipeId != value))
				{
					this._RecipeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyProcedure", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MyProcedure
		{
			get
			{
				return this._MyProcedure;
			}
			set
			{
				if ((this._MyProcedure != value))
				{
					this._MyProcedure = value;
				}
			}
		}
	}
	
	public partial class GetIngredientsResult
	{
		
		private int _IngredientId;
		
		private int _RecipeID;
		
		private int _Quantity;
		
		private string _Unit;
		
		private string _Ingredient;
		
		public GetIngredientsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientId", DbType="Int NOT NULL")]
		public int IngredientId
		{
			get
			{
				return this._IngredientId;
			}
			set
			{
				if ((this._IngredientId != value))
				{
					this._IngredientId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeID", DbType="Int NOT NULL")]
		public int RecipeID
		{
			get
			{
				return this._RecipeID;
			}
			set
			{
				if ((this._RecipeID != value))
				{
					this._RecipeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ingredient", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Ingredient
		{
			get
			{
				return this._Ingredient;
			}
			set
			{
				if ((this._Ingredient != value))
				{
					this._Ingredient = value;
				}
			}
		}
	}
	
	public partial class GetProceduresResult
	{
		
		private int _ProcedureId;
		
		private int _RecipeId;
		
		private string _MyProcedure;
		
		public GetProceduresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcedureId", DbType="Int NOT NULL")]
		public int ProcedureId
		{
			get
			{
				return this._ProcedureId;
			}
			set
			{
				if ((this._ProcedureId != value))
				{
					this._ProcedureId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeId", DbType="Int NOT NULL")]
		public int RecipeId
		{
			get
			{
				return this._RecipeId;
			}
			set
			{
				if ((this._RecipeId != value))
				{
					this._RecipeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyProcedure", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MyProcedure
		{
			get
			{
				return this._MyProcedure;
			}
			set
			{
				if ((this._MyProcedure != value))
				{
					this._MyProcedure = value;
				}
			}
		}
	}
	
	public partial class GetRecipeIDResult
	{
		
		private int _RecipeId;
		
		private string _RecipeName;
		
		private string _Difficulty;
		
		private string _RecipeType;
		
		private string _Comment;
		
		public GetRecipeIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeId", DbType="Int NOT NULL")]
		public int RecipeId
		{
			get
			{
				return this._RecipeId;
			}
			set
			{
				if ((this._RecipeId != value))
				{
					this._RecipeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipeName
		{
			get
			{
				return this._RecipeName;
			}
			set
			{
				if ((this._RecipeName != value))
				{
					this._RecipeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Difficulty", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Difficulty
		{
			get
			{
				return this._Difficulty;
			}
			set
			{
				if ((this._Difficulty != value))
				{
					this._Difficulty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipeType
		{
			get
			{
				return this._RecipeType;
			}
			set
			{
				if ((this._RecipeType != value))
				{
					this._RecipeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
	}
	
	public partial class GetRecipeIDfordeleteResult
	{
		
		private int _RecipeId;
		
		private string _RecipeName;
		
		private string _Difficulty;
		
		private string _RecipeType;
		
		private string _Comment;
		
		public GetRecipeIDfordeleteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeId", DbType="Int NOT NULL")]
		public int RecipeId
		{
			get
			{
				return this._RecipeId;
			}
			set
			{
				if ((this._RecipeId != value))
				{
					this._RecipeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipeName
		{
			get
			{
				return this._RecipeName;
			}
			set
			{
				if ((this._RecipeName != value))
				{
					this._RecipeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Difficulty", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Difficulty
		{
			get
			{
				return this._Difficulty;
			}
			set
			{
				if ((this._Difficulty != value))
				{
					this._Difficulty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipeType
		{
			get
			{
				return this._RecipeType;
			}
			set
			{
				if ((this._RecipeType != value))
				{
					this._RecipeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
	}
	
	public partial class GetRecipeNameResult
	{
		
		private int _RecipeId;
		
		private string _RecipeName;
		
		private string _Difficulty;
		
		private string _RecipeType;
		
		private string _Comment;
		
		public GetRecipeNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeId", DbType="Int NOT NULL")]
		public int RecipeId
		{
			get
			{
				return this._RecipeId;
			}
			set
			{
				if ((this._RecipeId != value))
				{
					this._RecipeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipeName
		{
			get
			{
				return this._RecipeName;
			}
			set
			{
				if ((this._RecipeName != value))
				{
					this._RecipeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Difficulty", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Difficulty
		{
			get
			{
				return this._Difficulty;
			}
			set
			{
				if ((this._Difficulty != value))
				{
					this._Difficulty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipeType
		{
			get
			{
				return this._RecipeType;
			}
			set
			{
				if ((this._RecipeType != value))
				{
					this._RecipeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
	}
	
	public partial class InsertIntoRecipeResult
	{
		
		private int _RecipeId;
		
		public InsertIntoRecipeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeId", DbType="Int NOT NULL")]
		public int RecipeId
		{
			get
			{
				return this._RecipeId;
			}
			set
			{
				if ((this._RecipeId != value))
				{
					this._RecipeId = value;
				}
			}
		}
	}
	
	public partial class mainProcedureResult
	{
		
		private int _RecipeID;
		
		public mainProcedureResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeID", DbType="Int NOT NULL")]
		public int RecipeID
		{
			get
			{
				return this._RecipeID;
			}
			set
			{
				if ((this._RecipeID != value))
				{
					this._RecipeID = value;
				}
			}
		}
	}
	
	public partial class GetIngredientsbyRecipeIDResult
	{
		
		private int _IngredientId;
		
		private int _RecipeID;
		
		private int _Quantity;
		
		private string _Unit;
		
		private string _Ingredient;
		
		public GetIngredientsbyRecipeIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientId", DbType="Int NOT NULL")]
		public int IngredientId
		{
			get
			{
				return this._IngredientId;
			}
			set
			{
				if ((this._IngredientId != value))
				{
					this._IngredientId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeID", DbType="Int NOT NULL")]
		public int RecipeID
		{
			get
			{
				return this._RecipeID;
			}
			set
			{
				if ((this._RecipeID != value))
				{
					this._RecipeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ingredient", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Ingredient
		{
			get
			{
				return this._Ingredient;
			}
			set
			{
				if ((this._Ingredient != value))
				{
					this._Ingredient = value;
				}
			}
		}
	}
	
	public partial class InsertIntoMyRecipeResult
	{
		
		private int _RecipeID;
		
		private string _RecipeName;
		
		private string _RecipeType;
		
		private System.Nullable<int> _IngredientID;
		
		private System.Nullable<int> _ProcedureId;
		
		public InsertIntoMyRecipeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeID", DbType="Int NOT NULL")]
		public int RecipeID
		{
			get
			{
				return this._RecipeID;
			}
			set
			{
				if ((this._RecipeID != value))
				{
					this._RecipeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipeName
		{
			get
			{
				return this._RecipeName;
			}
			set
			{
				if ((this._RecipeName != value))
				{
					this._RecipeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipeType
		{
			get
			{
				return this._RecipeType;
			}
			set
			{
				if ((this._RecipeType != value))
				{
					this._RecipeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientID", DbType="Int")]
		public System.Nullable<int> IngredientID
		{
			get
			{
				return this._IngredientID;
			}
			set
			{
				if ((this._IngredientID != value))
				{
					this._IngredientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcedureId", DbType="Int")]
		public System.Nullable<int> ProcedureId
		{
			get
			{
				return this._ProcedureId;
			}
			set
			{
				if ((this._ProcedureId != value))
				{
					this._ProcedureId = value;
				}
			}
		}
	}
	
	public partial class GetProcedureIDResult
	{
		
		private int _ProcedureId;
		
		private int _RecipeId;
		
		private string _MyProcedure;
		
		public GetProcedureIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcedureId", DbType="Int NOT NULL")]
		public int ProcedureId
		{
			get
			{
				return this._ProcedureId;
			}
			set
			{
				if ((this._ProcedureId != value))
				{
					this._ProcedureId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeId", DbType="Int NOT NULL")]
		public int RecipeId
		{
			get
			{
				return this._RecipeId;
			}
			set
			{
				if ((this._RecipeId != value))
				{
					this._RecipeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyProcedure", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MyProcedure
		{
			get
			{
				return this._MyProcedure;
			}
			set
			{
				if ((this._MyProcedure != value))
				{
					this._MyProcedure = value;
				}
			}
		}
	}
	
	public partial class GetIngredientIDResult
	{
		
		private int _IngredientId;
		
		public GetIngredientIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientId", DbType="Int NOT NULL")]
		public int IngredientId
		{
			get
			{
				return this._IngredientId;
			}
			set
			{
				if ((this._IngredientId != value))
				{
					this._IngredientId = value;
				}
			}
		}
	}
	
	public partial class GetAllRecipeResult
	{
		
		private int _RecipeId;
		
		private string _RecipeName;
		
		private string _RecipeType;
		
		private string _difficulty;
		
		public GetAllRecipeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeId", DbType="Int NOT NULL")]
		public int RecipeId
		{
			get
			{
				return this._RecipeId;
			}
			set
			{
				if ((this._RecipeId != value))
				{
					this._RecipeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipeName
		{
			get
			{
				return this._RecipeName;
			}
			set
			{
				if ((this._RecipeName != value))
				{
					this._RecipeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipeType
		{
			get
			{
				return this._RecipeType;
			}
			set
			{
				if ((this._RecipeType != value))
				{
					this._RecipeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_difficulty", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string difficulty
		{
			get
			{
				return this._difficulty;
			}
			set
			{
				if ((this._difficulty != value))
				{
					this._difficulty = value;
				}
			}
		}
	}
	
	public partial class GetRecipeIngredientsResult
	{
		
		private string _Ingredient;
		
		private int _Quantity;
		
		private string _Unit;
		
		public GetRecipeIngredientsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ingredient", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Ingredient
		{
			get
			{
				return this._Ingredient;
			}
			set
			{
				if ((this._Ingredient != value))
				{
					this._Ingredient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
	}
	
	public partial class GetRecipeInfoResult
	{
		
		private string _RecipeName;
		
		private string _RecipeType;
		
		private string _Difficulty;
		
		private string _Comment;
		
		public GetRecipeInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipeName
		{
			get
			{
				return this._RecipeName;
			}
			set
			{
				if ((this._RecipeName != value))
				{
					this._RecipeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipeType
		{
			get
			{
				return this._RecipeType;
			}
			set
			{
				if ((this._RecipeType != value))
				{
					this._RecipeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Difficulty", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Difficulty
		{
			get
			{
				return this._Difficulty;
			}
			set
			{
				if ((this._Difficulty != value))
				{
					this._Difficulty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
	}
	
	public partial class GetRecipeProceduresResult
	{
		
		private int _ProcedureId;
		
		private string _MyProcedure;
		
		public GetRecipeProceduresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcedureId", DbType="Int NOT NULL")]
		public int ProcedureId
		{
			get
			{
				return this._ProcedureId;
			}
			set
			{
				if ((this._ProcedureId != value))
				{
					this._ProcedureId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyProcedure", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MyProcedure
		{
			get
			{
				return this._MyProcedure;
			}
			set
			{
				if ((this._MyProcedure != value))
				{
					this._MyProcedure = value;
				}
			}
		}
	}
	
	public partial class GetRecipeIngredientsResultResult
	{
		
		private string _Ingredient;
		
		private int _Quantity;
		
		private string _Unit;
		
		public GetRecipeIngredientsResultResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ingredient", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Ingredient
		{
			get
			{
				return this._Ingredient;
			}
			set
			{
				if ((this._Ingredient != value))
				{
					this._Ingredient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
	}
	
	public partial class GetRecipeIngredientResult
	{
		
		private string _Ingredient;
		
		private int _Quantity;
		
		private string _Unit;
		
		private int _IngredientId;
		
		public GetRecipeIngredientResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ingredient", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Ingredient
		{
			get
			{
				return this._Ingredient;
			}
			set
			{
				if ((this._Ingredient != value))
				{
					this._Ingredient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientId", DbType="Int NOT NULL")]
		public int IngredientId
		{
			get
			{
				return this._IngredientId;
			}
			set
			{
				if ((this._IngredientId != value))
				{
					this._IngredientId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
