<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Viewrecipe.aspx.cs" Inherits="Webtest2.Viewrecipe" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
                 
    <%--<asp:Button ID="btnEditRecipe" runat="server" text="Edit Recipe Info" OnClick="btnEditRecipe_OnClick"/>--%>

    <%--<asp:Button ID="btnSaveRecipe" runat="server" text="Save Changes"  OnClick="btnSaveRecipe_OnClick" Visible="false"/>--%>
    </div>
        <fieldset>
            <legend>Recipe Info</legend>
        <div>
            <asp:Label ID="lblrecipename" runat="server" Text="Recipe name" AssociatedControlID="TxtRecipename"></asp:Label>
            <asp:TextBox ID="TxtRecipename" runat="server" ReadOnly="false"></asp:TextBox>
            <asp:Label ID="lblrecipetype" runat="server" Text="Recipe type" AssociatedControlID="TxtRecipetype"></asp:Label>
            <asp:TextBox ID="TxtRecipetype" runat="server" ReadOnly="false"></asp:TextBox>
            <asp:Label ID="lbldifficulty" runat="server" Text="Difficulty" AssociatedControlID="TxtDifficulty"></asp:Label>
            <asp:TextBox ID="TxtDifficulty" runat="server" ReadOnly="false"></asp:TextBox>
            <asp:Label ID="lblcomment" runat="server" Text="Recipe comment" AssociatedControlID="Txtcomment"></asp:Label>
            <asp:TextBox ID="Txtcomment" runat="server" ReadOnly="false"></asp:TextBox>

        </div>
        <div>
            <%--<asp:Button ID="btnEditRecipe" runat="server" Text="Edit" OnClick="btnEditRecipe_OnClick" />--%>
            <asp:Button ID="btnSaveRecipeChanges" runat="server" Text="Save Changes" OnClick="btnSaveRecipe_OnClick" Visible="true"/>
        </div>

        </fieldset>

        <fieldset>

            

                <legend>Ingredient Info</legend>

                 <%--   <asp:GridView ID="GridViewIngredients" runat="server" datakeynames ="Ingredient" AutoGenerateDeleteButton="True" 
                    OnRowDeleting="DeletingRow"  AutoGenerateColumns="False" OnRowDataBound="GridViewIngredients_RowDataBound" OnSelectedIndexChanged="GridViewIngredients_SelectedIndexChanged">--%>

                <asp:GridView ID="GridViewIngredients" runat="server" AllowPaging="true" AutoGenerateColumns="false" OnPageIndexChanging="GridViewIngredients_OnPageIndexChanging" OnRowDeleting="DeletingRow" OnRowCommand="GridViewIngredients_RowCommand" DataKeyNames="Ingredient">

                    <Columns>
                        <%--<asp:BoundField DataField="IngredientId" HeaderText="IngredientID" SortExpression="IngredientID" />--%>
                        <asp:BoundField DataField="Ingredient" HeaderText="Ingredient" SortExpression="Ingredient" />
                        <asp:BoundField DataField="Quantity" HeaderText="Quantity" SortExpression="Quantity" />
                        <asp:BoundField DataField="Unit" HeaderText="Unit" SortExpression="Unit" />
                        <asp:BoundField DataField="IngredientId" HeaderText="IngredientId" SortExpression="IngredientId" />
                         <asp:TemplateField HeaderText="">
                            <ItemTemplate>
                                <asp:LinkButton ID="deletebuttonProcedure" runat="server" Text="Delete" CommandName="Delete" CommandArgument='<%# Eval("IngredientId") %>'></asp:LinkButton>
          
                            </ItemTemplate>

                        </asp:TemplateField>
           
                    </Columns>
                
                </asp:GridView>
          
          </fieldset>

        <div>
            <asp:Label ID="lblAddIngredient" runat="server" Text="Ingredient: " AssociatedControlID="txtAddIngredientname" ></asp:Label>
            <asp:TextBox ID="txtAddIngredientname" runat="server">
            </asp:TextBox>
        
        </div>
        <div>
            <asp:Label ID="lblAddQuantity" runat="server" Text="Quantity: " AssociatedControlID="txtAddIngredientQuantity" ></asp:Label>
            <asp:TextBox ID="txtAddIngredientQuantity" runat="server">
            </asp:TextBox>

        </div>
        <div>
             <asp:Label ID="lblAddUnit" runat="server" Text="Unit: " AssociatedControlID="txtAddIngredientUnit" ></asp:Label>
            <asp:TextBox ID="txtAddIngredientUnit" runat="server">
            </asp:TextBox>

                <asp:Button ID="btnAddAdditionalIngredient" runat="server" text="Add Ingredient to Recipe!" OnClick="btnAddAdditionalIngredient_OnClick"/>

        </div>

             <fieldset>

            

                <legend>Procedure Info</legend>

                    <%--<asp:GridView ID="GridViewProcedure" runat="server" datakeynames ="ProcedureID"  
                      AutoGenerateColumns="False" OnRowDataBound="GridViewProcedure_RowDataBound" OnRowCommand="GridViewProcedure_RowCommand" OnSelectedIndexChanged="GridViewProcedure_SelectedIndexChanged" SelectedIndex="0">--%>
                     <asp:GridView ID="GridViewProcedure" runat="server" AllowPaging="true" AutoGenerateColumns="false" OnPageIndexChanging="GridViewProcedure_OnPageIndexChanging" OnRowDeleting="DeleteRow" OnRowCommand="GridViewProcedure_RowCommand" DataKeyNames="ProcedureID">
                 
                 <Columns>
                        <asp:BoundField DataField="ProcedureId" HeaderText="ProcedureID" SortExpression="ProcedureID" />
                        <asp:BoundField DataField="MyProcedure" HeaderText="Procedure" SortExpression="Procedure" />
                        <asp:TemplateField HeaderText="">
                            <ItemTemplate>
                                <asp:LinkButton ID="deletebuttonProcedure" runat="server" Text="Delete" CommandName="Delete" CommandArgument='<%# Eval("ProcedureId") %>'></asp:LinkButton>
                            
                            
                            </ItemTemplate>

                        </asp:TemplateField>
                        
                    </Columns>
                
                    </asp:GridView>

          
          </fieldset>    

         <div>
            <asp:Label ID="lbladdProcedure" runat="server" Text="Procedure: " AssociatedControlID="txtaddAdditionalProcedure" ></asp:Label>
            <asp:TextBox ID="txtaddAdditionalProcedure" runat="server">
            </asp:TextBox>
        
           <asp:Button ID="btnaddAdditionalProcedure" runat="server" text="Add Procedure to Recipe!" OnClick="btnAddAdditionalProcedure_OnClick"/>

        </div>
                 <%--<asp:Button ID="btnAddAdditionalIngredient" runat="server" text="Add Ingredient to Recipe!" OnClick="btnAddAdditionalIngredient_OnClick"/>
                 </div>

        <fieldset>
                <legend>Additional Ingredient info</legend>


         <div class="row">

                      <asp:GridView ID="GridViewAdditionalIngredients" runat="server"  datakeynames ="additionalIngredientID"
                    AutoGenerateDeleteButton="True" EmptyDataText="No records Found"
                    OnRowDeleting="DeleteRowAddIngredient" AutoGenerateColumns="False" >
                    <Columns>
                        <asp:BoundField DataField="Ingredient" HeaderText="Ingredient" />
                        <asp:BoundField DataField="Quantity" HeaderText="Quantity"         />                        
                        <asp:BoundField DataField="Unit" HeaderText="Unit"  />                        
                                              
                       
                    </Columns>
                  
                </asp:GridView>
             </div>

                <asp:Button ID="btnOpenAddingredient" runat="server" text="Add A ingredient"  OnClick="btnOpenAddingredient_OnClick"/>

             </fieldset>
--%>


    </form>
</body>
</html>
